# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoWindow(object):
    def setupUi(self, InfoWindow):
        InfoWindow.setObjectName("InfoWindow")
        InfoWindow.resize(352, 407)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("timetable_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InfoWindow.setWindowIcon(icon)
        InfoWindow.setStyleSheet("background-color: rgb(74, 112, 139);")
        self.pushButton_back = QtWidgets.QPushButton(InfoWindow)
        self.pushButton_back.setGeometry(QtCore.QRect(30, 250, 113, 32))
        self.pushButton_back.setStyleSheet("background-color: rgb(108, 166, 205);\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"padding: 3 8px;")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_save = QtWidgets.QPushButton(InfoWindow)
        self.pushButton_save.setGeometry(QtCore.QRect(190, 250, 113, 32))
        self.pushButton_save.setStyleSheet("background-color: rgb(108, 166, 205);\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"padding: 3 8px;\n"
"")
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_lession = QtWidgets.QLabel(InfoWindow)
        self.label_lession.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_lession.setObjectName("label_lession")
        self.lineEdit_name = QtWidgets.QLineEdit(InfoWindow)
        self.lineEdit_name.setGeometry(QtCore.QRect(210, 20, 121, 21))
        self.lineEdit_name.setStyleSheet("background-color: rgb(108, 166, 205);\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"padding: 3 8px;")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_session = QtWidgets.QLabel(InfoWindow)
        self.label_session.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_session.setObjectName("label_session")
        self.label_notable = QtWidgets.QLabel(InfoWindow)
        self.label_notable.setGeometry(QtCore.QRect(20, 140, 171, 16))
        self.label_notable.setObjectName("label_notable")
        self.label_lecture = QtWidgets.QLabel(InfoWindow)
        self.label_lecture.setGeometry(QtCore.QRect(20, 170, 131, 16))
        self.label_lecture.setObjectName("label_lecture")
        self.label_dopsa = QtWidgets.QLabel(InfoWindow)
        self.label_dopsa.setGeometry(QtCore.QRect(20, 200, 131, 16))
        self.label_dopsa.setObjectName("label_dopsa")
        self.checkBox_session = QtWidgets.QCheckBox(InfoWindow)
        self.checkBox_session.setGeometry(QtCore.QRect(210, 50, 87, 20))
        self.checkBox_session.setText("")
        self.checkBox_session.setObjectName("checkBox_session")
        self.checkBox_notable = QtWidgets.QCheckBox(InfoWindow)
        self.checkBox_notable.setGeometry(QtCore.QRect(210, 140, 87, 20))
        self.checkBox_notable.setText("")
        self.checkBox_notable.setObjectName("checkBox_notable")
        self.checkBox_lection = QtWidgets.QCheckBox(InfoWindow)
        self.checkBox_lection.setGeometry(QtCore.QRect(210, 170, 87, 20))
        self.checkBox_lection.setText("")
        self.checkBox_lection.setObjectName("checkBox_lection")
        self.label_7 = QtWidgets.QLabel(InfoWindow)
        self.label_7.setGeometry(QtCore.QRect(0, 220, 301, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_profile = QtWidgets.QLabel(InfoWindow)
        self.label_profile.setGeometry(QtCore.QRect(20, 110, 161, 16))
        self.label_profile.setObjectName("label_profile")
        self.checkBox_profile = QtWidgets.QCheckBox(InfoWindow)
        self.checkBox_profile.setGeometry(QtCore.QRect(210, 110, 87, 20))
        self.checkBox_profile.setText("")
        self.checkBox_profile.setObjectName("checkBox_profile")
        self.label_session_2 = QtWidgets.QLabel(InfoWindow)
        self.label_session_2.setGeometry(QtCore.QRect(20, 80, 161, 16))
        self.label_session_2.setObjectName("label_session_2")
        self.doubleSpinBox_prepod = QtWidgets.QDoubleSpinBox(InfoWindow)
        self.doubleSpinBox_prepod.setGeometry(QtCore.QRect(210, 80, 62, 22))
        self.doubleSpinBox_prepod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_prepod.setMaximum(1.0)
        self.doubleSpinBox_prepod.setSingleStep(0.05)
        self.doubleSpinBox_prepod.setObjectName("doubleSpinBox_prepod")
        self.doubleSpinBox_dopsa = QtWidgets.QDoubleSpinBox(InfoWindow)
        self.doubleSpinBox_dopsa.setGeometry(QtCore.QRect(210, 200, 62, 22))
        self.doubleSpinBox_dopsa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_dopsa.setMaximum(1.0)
        self.doubleSpinBox_dopsa.setSingleStep(0.05)
        self.doubleSpinBox_dopsa.setObjectName("doubleSpinBox_dopsa")

        self.retranslateUi(InfoWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoWindow)

    def retranslateUi(self, InfoWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoWindow.setWindowTitle(_translate("InfoWindow", "Изменение информации"))
        self.pushButton_back.setText(_translate("InfoWindow", "Назад"))
        self.pushButton_save.setText(_translate("InfoWindow", "Сохранить"))
        self.label_lession.setText(_translate("InfoWindow", "Название предмета"))
        self.label_session.setText(_translate("InfoWindow", "Наличие сессии"))
        self.label_notable.setText(_translate("InfoWindow", "Проверка посещаемости"))
        self.label_lecture.setText(_translate("InfoWindow", "Лекция"))
        self.label_dopsa.setText(_translate("InfoWindow", "Вероятность допсы"))
        self.label_profile.setText(_translate("InfoWindow", "Профильность"))
        self.label_session_2.setText(_translate("InfoWindow", "Оценка преподавателя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InfoWindow = QtWidgets.QWidget()
    ui = Ui_InfoWindow()
    ui.setupUi(InfoWindow)
    InfoWindow.show()
    sys.exit(app.exec_())
